<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INFLAP117" name="com.testrunner.ss.TestRunner" tests="1" failures="0" timestamp="13 Jun 2019 12:06:26 GMT" time="44.102" errors="1">
  <testcase name="feature" time="44.102" classname="com.testrunner.ss.TestRunner">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	Completed count is incorrect expected [64] but found [69],
	Incomplete count is incorrect expected [80] but found [78],
	Processed count is incorrect expected [144] but found [147],
	Zillow count is incorrect expected [48] but found [47],
	Third Party count is incorrect expected [1510] but found [1509],
	Corrupted count is incorrect expected [0] but found [3]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
Completed count is incorrect expected [64] but found [69],
Incomplete count is incorrect expected [80] but found [78],
Processed count is incorrect expected [144] but found [147],
Zillow count is incorrect expected [48] but found [47],
Third Party count is incorrect expected [1510] but found [1509],
Corrupted count is incorrect expected [0] but found [3]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
Completed count is incorrect expected [64] but found [69],
Incomplete count is incorrect expected [80] but found [78],
Processed count is incorrect expected [144] but found [147],
Zillow count is incorrect expected [48] but found [47],
Third Party count is incorrect expected [1510] but found [1509],
Corrupted count is incorrect expected [0] but found [3]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.stepdefinitions.ss.CreateCompany.values_on_ui_should_match_with_that_of_db(CreateCompany.java:5250)
at âœ½.Then Values on UI should match with that of DB(features/CreateCompany.feature:93)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.testrunner.ss.TestRunner -->
